name: my-workflow

on:
    push:
        branches: ['main']
    pull_request:


jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test
      - run: bun index.ts
      - run: bun run build
